<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Api\Module'                        => __DIR__ . '/Module.php',
    'Api\Controller\ApiController' => __DIR__ . '/src/Api/Controller/ApiController.php',

);
