<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Data in Table~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<table class="table table-bordered">
    <thead>
    <tr>
        <th>User Name</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Sex</th>
        <th>Address</th>
        <th>Phone</th>
        <th>E-Mail</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody id="ttable">

    </tbody>
</table>
<script type="text/x-jQuery-tmpl" id="table">
        <tr class="parents text-center">
			<td><a href="" data-id="${user_id}">${user_name}</a></td>
			<td>${first_name}</td>
			<td>${last_name}</td>
			<td>${sex}</td>
			<td>${address}</td>
			<td>${phone}</td>
			<td>${email}</td>
			<td>
			    <button type="button" class="btn-edit btn btn-info" data-id="${user_id}">Edit</button> /
			    <button type="button" class="btn-delete btn btn-danger" data-id="${user_id}" >Delete</button>
            </td>
		</tr>
</script>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Data in Table~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

<!--~~~~~~~~~~~~~~~~~~~~~~~~Start Edit Record in Table~~~~~~~~~~~~~~~~~~~~~~~~~-->
<br>
<form class="edit-place hidden" method="<?php echo $this->basepath();?>/api/">

</form>
<script type="text/x-jQuery-tmpl" class="dataidapi">
    <div class="row">
        <div class="col-md-3"><input class="form-control" name="username" value="${user_name}" type="text" placeholder="Input Username..."></div>
        <div class="col-md-3"><input class="form-control" name="userpwd" value="${user_pwd}" type="text" placeholder="Input Password..."></div>
        <div class="col-md-3"><input class="form-control" name="firstname" value="${first_name}" type="text" placeholder="Input First Name..."></div>
        <div class="col-md-3"><input class="form-control" name="lastname" value="${last_name}" type="text" placeholder="Input Last Name..."></div>
    </div><br>
    <div class="row">
        <div class="col-md-3"><select class="sex form-control"><option value="male">Male</option><option value="female">Female</option></select></div>
        <div class="col-md-3"><input class="form-control" name="address" value="${address}" type="text" placeholder="Input Your Address..."></div>
        <div class="col-md-3"><input class="form-control" name="phone" value="${phone}" type="number" placeholder="012334455..."></div>
        <div class="col-md-3"><input class="form-control" name="email" value="${email}" type="mail" placeholder="Input Your E-mail..."></div>
    </div><br>
    <div class="row">
        <div class="col-md-3"><button class="btn-edit-user btn btn-success form-control" type="button" data-id="${user_id}">Edit</button></div>
    </div><br>
</script>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~End Edit Record in Table~~~~~~~~~~~~~~~~~~~~~~~~~-->
<script type="text/javascript">
    var _basePath = '<?php echo $this->basePath()?>/';
    var API = function(){
        this.requestUrl = function(url, onSuccess, onError){
            $.ajax({
                async: false,
                url: url,
                contentType: 'application/json',
                success: function(data, textStatus, xhr){
                    onSuccess(data, textStatus, xhr);
                },
                error: function(xhr, textStatus, errorThrown){
                    if(null != onError) {
                        error(xhr, textStatus, errorThrown);
                    }
                }
            });
        };
    };

    var getList = function(url){
        var fn = function(){};
        fn.prototype = new API();
        fn.prototype.getApi = function ( onSuccess, onError ){
            this.requestUrl( _basePath + url, onSuccess, onError );
        };

        fn.prototype.getData = function () {
            var data = null;
            this.getApi(function ( re ){
                data = re;
            });
            return data;
        };

        var obj = new fn();
        return obj.getData();
    };

/*~~~~~~~~~~Start Data append Into Table~~~~~~~~~~~~~~*/
    var getData = getList('api');
    $('#table').tmpl(getData['data']).appendTo('#ttable');
/*~~~~~~~~~~~~End Data append Into Table~~~~~~~~~~~~~~*/




/*~~~~~~~~~~~~~~Start Edit with Ajax~~~~~~~~~~~~~~~~~~*/
    $('.btn-edit').click(function(){
        $('.table').addClass('hidden');
        $('.edit-place').removeClass('hidden');

        var id = $(this).attr('data-id');
        var getid = getList('api/'+id);
        $('.dataidapi').tmpl(getid['data']).appendTo('.edit-place');

        $('.btn-edit-user').click(function(){
            var userid = $(this).attr('data-id');
            var username = $("input[name*='username']").val();
            var userpwd = $("input[name*='userpwd']").val();
            var firstname = $("input[name*='firstname']").val();
            var lastname = $("input[name*='lastname']").val();
            var sex = $(".sex").val();
            var address = $("input[name*='address']").val();
            var phone = $("input[name*='phone']").val();
            var email = $("input[name*='email']").val();
            var url = "<?php echo $this->basepath();?>/api/"+userid;

            $.ajax({
                async: false,
                url: url,
                type:'PUT',
                data: {"user_name":username,"user_pwd":userpwd,"first_name":firstname,"last_name":lastname,"sex":sex,"address":address,"phone":phone,"email":email},
                dataType: 'application/json',
                success: function(){
                    alert(123);
                }
            });
        });
    });

    /*~~~~~~~~~~~~~~~End Edit with Ajax~~~~~~~~~~~~~~~~~~*/






    $('.btn-delete').click(function(){
        var id = $(this).attr('data-id');
        alert("Are you sure! You want to delete this record?");

    });
</script>


