<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Start Data in Table~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<table class="table table-bordered">
    <thead>
    <tr>
        <th>User Name</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Sex</th>
        <th>Address</th>
        <th>Phone</th>
        <th>E-Mail</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody id="ttable">

    </tbody>
</table>
<script type="text/x-jQuery-tmpl" id="table">
        <tr class="parents">
			<td>${user_id}&nbsp;&nbsp;&nbsp;&nbsp;${user_name}</td>
			<td>${first_name}</td>
			<td>${last_name}</td>
			<td>${sex}</td>
			<td>${address}</td>
			<td>${phone}</td>
			<td>${email}</td>
			<td>
			    <button type="button" class="btn-edit btn btn-info" data-id="${user_id}">Edit</button> /
			    <button type="button" class="btn-delete btn btn-danger" data-id="${user_id}" >Delete</button>
            </td>
		</tr>
</script>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~End Data in Table~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

<!--~~~~~~~~~~~~~~~~~~~~~~~~Start Edit Record in Table~~~~~~~~~~~~~~~~~~~~~~~~~-->
<br>
<form class="edit-place hidden">
    <div class="row">
        <div class="col-md-3"><input class="form-control" name="username" type="text" placeholder="Input Your Name..."></div>
        <div class="col-md-3"><input class="form-control" name="userpwd" type="text" placeholder="Input Your Name..."></div>
        <div class="col-md-3"><input class="form-control" name="firstname" type="text" placeholder="Input Your Name..."></div>
        <div class="col-md-3"><input class="form-control" name="lastname" type="text" placeholder="Input Your Name..."></div>
    </div><br>
    <div class="row">
        <div class="col-md-3"><select name="sex" class="form-control"><option value="male">Male</option><option value="female">Female</option></select></div>
        <div class="col-md-3"><input class="form-control" name="address" type="text" placeholder="Input Your Address..."></div>
        <div class="col-md-3"><input class="form-control" name="phone" type="number" placeholder="012334455..."></div>
        <div class="col-md-3"><input class="form-control" name="email" type="text" placeholder="Input Your E-mail..."></div>
    </div>
</form>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~End Edit Record in Table~~~~~~~~~~~~~~~~~~~~~~~~~-->
<script type="text/javascript">
    var API = function(){
        this.requestUrl = function(url, onSuccess, onError){
            $.ajax({
                async: false,
                url: url,
                contentType: 'application/json',
                success: function(data, textStatus, xhr){
                    onSuccess(data, textStatus, xhr);
                },
                error: function(xhr, textStatus, errorThrown){
                    if(null != onError) {
                        error(xhr, textStatus, errorThrown);
                    }
                }
            });
        };
    };

    var getList = function(url){
        var _basePath = '<?php echo $this->basePath()?>/';
        var fn = function(){};
        fn.prototype = new API();
        fn.prototype.getApi = function ( onSuccess, onError ){
            this.requestUrl( _basePath + url, onSuccess, onError );
        };

        fn.prototype.getData = function () {
            var data = null;
            this.getApi(function ( re ){
                data = re;
            });
            return data;
        };

        var obj = new fn();
        return obj.getData();
    };

/*~~~~~~~~~~Start Data append Into Table~~~~~~~~~~~~~~*/
    var getData = getList('api');
    $('#table').tmpl(getData['data']).appendTo('#ttable');
/*~~~~~~~~~~~~End Data append Into Table~~~~~~~~~~~~~~*/




/*~~~~~~~~~~~~~~Start Edit with Ajax~~~~~~~~~~~~~~~~~~*/
    $('.btn-edit').click(function(){
        $('.table').addClass('hidden');
        $('.edit-place').removeClass('hidden');

        var id = $(this).attr('data-id');
        var url = '<?php echo $this->basePath()?>/api/'+id;
        alert(url);
    });
    /*~~~~~~~~~~~~~~~End Edit with Ajax~~~~~~~~~~~~~~~~~~*/

    $('.btn-delete').click(function(){
        var id = $(this).attr('data-id');
        alert("Are you sure! You want to delete this record?");

    });
</script>


